### PR TITLE
Add SSL option

### PR DESCRIPTION
**Pull request by aChinKaiWu**

### CODE REVIEW

**Comment by cwc** [comment]
An SSL option would be great! Only concern I have with this patch is whether HTTPoison is cool with being passed a value of `nil` - in the event the option wasn't set. Does it still work? I'll try to find time to test it myself.

**Comment by aChinKaiWu** [comment]
> An SSL option would be great! Only concern I have with this patch is whether HTTPoison is cool with being passed a value of `nil` - in the event the option wasn't set. Does it still work? I'll try to find time to test it myself.

It still works, but error returns.

```ex
  @options [
    headers: [
      {"Accept", "text/event-stream"},
    ],
    recv_timeout: :infinity,
  ]

  EventsourceEx.new(url, @options)
```

```
{:error,
 {%HTTPoison.Error{id: nil, reason: {:tls_alert, 'unknown ca'}},
  [
    {HTTPoison, :request!, 5, [file: 'lib/httpoison.ex', line: 128]},
    {EventsourceEx, :init, 1, [file: 'lib/eventsource_ex.ex', line: 20]},
    {:gen_server, :init_it, 2, [file: 'gen_server.erl', line: 365]},
    {:gen_server, :init_it, 6, [file: 'gen_server.erl', line: 333]},
    {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 247]}
  ]}}
```

**Comment by cwc** [comment]
I thought it might. Maybe try `ssl = opts[:ssl] || false`? Though I'm not sure what will happen if `ssl = false` is set with an HTTPS URL supplied. 🤔

**Comment by AtibaBryan** [comment]
As a dev wanting to stream on some tls only apis with elixir I would greatly appreciate this pr 👍

**Comment by cwc** [comment]
Merged in #7.

**Pull request closed without merging**
